// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  default: {
    "profile-card": {
      name: "profile-card",
      type: "components:example",
      // registryDependencies: ["button", "card", "input", "label", "select"],
      component: React.lazy(
        () => import("@/registry/default/example/profile-card")
      ),
      files: ["registry/default/example/profile-card.tsx"],
    },
  },
}
